---

- name: Debian - Install apt-transport-https
  become: yes
  apt: name=apt-transport-https state=present
  when: i2_use_repository

- name: Debian - Add Icinga 2 repository key
  become: yes
  apt_key: url="{{ i2_apt_key }}" state=present
  when: i2_use_repository and i2_apt_key

- name: Debian - Add Icinga 2 repository
  become: yes
  apt_repository: repo={{ item.repo }} state={{ item.state}}
  with_items:
    - { repo: "{{ i2_apt_url }}", state: "present" }
  when: i2_use_repository
